---
name: pull request checks
"on":
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
  statuses: write
  actions: read
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fail if no build ID or component ID
        uses: ./
        with:
          org_id: ${{ secrets.test_org_id }}
          api_token: ${{ secrets.test_api_token }}
          api_url: ${{ secrets.test_api_url }}
        continue-on-error: true
      - name: Releases with component ID
        uses: ./
        with:
          org_id: ${{ secrets.test_org_id }}
          api_token: ${{ secrets.test_api_token }}
          component_id: ${{ secrets.test_component_id }}
          api_url: ${{ secrets.test_api_url }}
      - name: Releases with build ID
        uses: ./
        with:
          org_id: ${{ secrets.test_org_id }}
          api_token: ${{ secrets.test_api_token }}
          build_id: ${{ secrets.test_build_id }}
          api_url: ${{ secrets.test_api_url }}
      - name: Releases with component ID and auto-build
        uses: ./
        with:
          org_id: ${{ secrets.test_org_id }}
          api_token: ${{ secrets.test_api_token }}
          component_id: ${{ secrets.test_component_id }}
          auto_build: true
          api_url: ${{ secrets.test_api_url }}
